package metrics;

/**
 * Project: Halstead
 * Package: metrics
 * Author:  Novemser
 * 2016/10/22
 */
public enum Dimension {
    LOC_BLANK,
    BRANCH_COUNT,
    CALL_PAIRS,
    LOC_CODE_AND_COMMENT,
    LOC_COMMENTS,
    CONDITION_COUNT,
    CYCLOMATIC_COMPLEXITY,
    CYCLOMATIC_DENSITY,
    DECISION_COUNT,
    DECISION_DENSITY,
    DESIGN_COMPLEXITY,
    DESIGN_DENSITY,
    EDGE_COUNT,
    ESSENTIAL_COMPLEXITY,
    ESSENTIAL_DENSITY,
    LOC_EXECUTABLE,
    PARAMETER_COUNT,
    GLOBAL_DATA_COMPLEXITY,
    GLOBAL_DATA_DENSITY,
    HALSTEAD_CONTENT,
    HALSTEAD_DIFFICULTY,
    HALSTEAD_EFFORT,
    HALSTEAD_ERROR_SET,
    HALSTEAD_LENGTH,
    HALSTEAD_LEVEL,
    HALSTEAD_PROGRAM_TIME,
    HALSTEAD_VOLUME,
    MAINTENANCE_SEVERITY,
    MODIFIED_CONDITION_COUNT,
    MULTIPLE_CONDITION_COUNT,
    NODE_COUNT,
    NORMALIZED_CYCLOMATIC_COMPLEXITY,
    NUM_OPERANDS,
    NUM_OPERATORS,
    NUM_UNIQUE_OPERANDS,
    NUM_UNIQUE_OPERATORS,
    NUMBER_OF_LINES,
    PERCENT_COMMENTS,
    LOC_TOTAL
}
